import type { Product, Category, Review } from '@/types/product'

export const categories: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Next-gen tech, gadgets, and audio gear engineered for the future.',
    imageUrl: '/images/categories/electronics.jpg',
    isFeatured: true,
    sortOrder: 1,
    productCount: 4,
  },
  {
    id: 'cat-lifestyle',
    name: 'Lifestyle',
    slug: 'lifestyle',
    description: 'Premium lifestyle essentials that define modern living.',
    imageUrl: '/images/categories/lifestyle.jpg',
    isFeatured: true,
    sortOrder: 2,
    productCount: 4,
  },
  {
    id: 'cat-accessories',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Statement pieces and daily carry gear built to last.',
    imageUrl: '/images/categories/accessories.jpg',
    isFeatured: true,
    sortOrder: 3,
    productCount: 4,
  },
]

export const products: Product[] = [
  // ─── ELECTRONICS ─────────────────────────
  {
    id: 'prod-001',
    name: 'Phantom Pro Wireless Earbuds',
    slug: 'phantom-pro-wireless-earbuds',
    description: 'Experience audio perfection with the Phantom Pro. Featuring custom 12mm titanium drivers, active noise cancellation, and 40-hour battery life. IPX5 water-resistant with a matte black stealth finish that turns heads. Seamless Bluetooth 5.3 connectivity with multi-device pairing. The earbuds that audiophiles and streetwear enthusiasts agree on.',
    shortDesc: 'Premium ANC earbuds with 40hr battery and titanium drivers.',
    price: 149.99,
    comparePrice: 199.99,
    costPrice: 45.00,
    sku: 'FNK-EP-001',
    categoryId: 'cat-electronics',
    images: ['/images/products/earbuds-1.jpg', '/images/products/earbuds-2.jpg'],
    tags: ['audio', 'wireless', 'anc', 'premium'],
    isFeatured: true,
    isTrending: true,
    isNew: true,
    inStock: true,
    stockCount: 234,
    weightGrams: 58,
    metadata: { color: 'Stealth Black', driver: '12mm Titanium' },
    rating: 4.8,
    reviewCount: 342,
    createdAt: '2025-12-01T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Volt Charge Station 5-in-1',
    slug: 'volt-charge-station-5-in-1',
    description: 'The ultimate charging command center. Simultaneously power your phone, earbuds, watch, tablet, and laptop with GaN 120W fast-charging technology. Aircraft-grade aluminum build with ambient LED status indicators. A single cable to rule them all. Compatible with all Qi2 and USB-C devices.',
    shortDesc: '120W GaN 5-in-1 charger with premium aluminum build.',
    price: 89.99,
    comparePrice: 129.99,
    costPrice: 28.00,
    sku: 'FNK-EC-002',
    categoryId: 'cat-electronics',
    images: ['/images/products/charger-1.jpg', '/images/products/charger-2.jpg'],
    tags: ['charging', 'gan', 'tech', 'desk-setup'],
    isFeatured: true,
    isTrending: false,
    isNew: true,
    inStock: true,
    stockCount: 567,
    weightGrams: 380,
    metadata: { wattage: '120W', material: 'Aluminum' },
    rating: 4.6,
    reviewCount: 189,
    createdAt: '2025-11-15T00:00:00Z',
    updatedAt: '2025-11-15T00:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Nebula Smart Speaker',
    slug: 'nebula-smart-speaker',
    description: 'Room-filling 360° sound meets smart home control. The Nebula features a custom-tuned 4-driver array, deep bass radiator, and voice assistant integration. Its mesmerizing LED ring syncs with your music in real-time. Crafted from recycled ocean plastics with a sound profile that rivals speakers twice the price.',
    shortDesc: '360° smart speaker with reactive LED ring and deep bass.',
    price: 199.99,
    comparePrice: null,
    costPrice: 62.00,
    sku: 'FNK-ES-003',
    categoryId: 'cat-electronics',
    images: ['/images/products/speaker-1.jpg', '/images/products/speaker-2.jpg'],
    tags: ['audio', 'smart-home', 'speaker', 'led'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    inStock: true,
    stockCount: 123,
    weightGrams: 1200,
    metadata: { drivers: '4-driver array', connectivity: 'WiFi + Bluetooth' },
    rating: 4.7,
    reviewCount: 256,
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Cipher Mechanical Keyboard',
    slug: 'cipher-mechanical-keyboard',
    description: 'The keyboard that feels like the future. Hot-swappable optical switches, per-key RGB with 16 million colors, gasket-mounted design for that perfect thock. CNC aluminum frame, PBT double-shot keycaps, and wireless tri-mode connectivity. Built for creators, coders, and gamers who refuse to compromise.',
    shortDesc: 'Hot-swappable optical mechanical keyboard with gasket mount.',
    price: 169.99,
    comparePrice: 219.99,
    costPrice: 55.00,
    sku: 'FNK-EK-004',
    categoryId: 'cat-electronics',
    images: ['/images/products/keyboard-1.jpg', '/images/products/keyboard-2.jpg'],
    tags: ['keyboard', 'mechanical', 'rgb', 'wireless'],
    isFeatured: true,
    isTrending: true,
    isNew: true,
    inStock: true,
    stockCount: 89,
    weightGrams: 920,
    metadata: { switches: 'Optical', layout: '75%' },
    rating: 4.9,
    reviewCount: 478,
    createdAt: '2025-12-10T00:00:00Z',
    updatedAt: '2025-12-10T00:00:00Z',
  },

  // ─── LIFESTYLE ────────────────────────────
  {
    id: 'prod-005',
    name: 'Aether Titanium Water Bottle',
    slug: 'aether-titanium-water-bottle',
    description: 'Pure hydration meets industrial design. Double-wall vacuum insulation keeps drinks ice cold for 36 hours or piping hot for 18. Grade 5 titanium body weighs just 280g. The magnetic twist cap never loosens accidentally. Available in Void Black and Brushed Steel. The last water bottle you will ever buy.',
    shortDesc: 'Grade 5 titanium bottle — 36hr cold, 18hr hot.',
    price: 79.99,
    comparePrice: null,
    costPrice: 22.00,
    sku: 'FNK-LB-005',
    categoryId: 'cat-lifestyle',
    images: ['/images/products/bottle-1.jpg', '/images/products/bottle-2.jpg'],
    tags: ['hydration', 'titanium', 'edc', 'premium'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    inStock: true,
    stockCount: 412,
    weightGrams: 280,
    metadata: { material: 'Grade 5 Titanium', capacity: '750ml' },
    rating: 4.8,
    reviewCount: 623,
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Eclipse LED Desk Lamp',
    slug: 'eclipse-led-desk-lamp',
    description: 'Redefine your workspace with the Eclipse. A floating ring of light powered by 120 LEDs with CRI 98+ color accuracy. Five color temperatures, infinite dimming, and a built-in wireless charging base. The articulating arm adjusts to any angle. Designed in collaboration with minimalist architects for the desk of the future.',
    shortDesc: 'CRI 98+ floating ring LED lamp with wireless charging base.',
    price: 129.99,
    comparePrice: 179.99,
    costPrice: 38.00,
    sku: 'FNK-LL-006',
    categoryId: 'cat-lifestyle',
    images: ['/images/products/lamp-1.jpg', '/images/products/lamp-2.jpg'],
    tags: ['lighting', 'desk-setup', 'wireless-charging', 'minimalist'],
    isFeatured: true,
    isTrending: false,
    isNew: true,
    inStock: true,
    stockCount: 198,
    weightGrams: 1500,
    metadata: { cri: '98+', leds: '120' },
    rating: 4.5,
    reviewCount: 167,
    createdAt: '2025-11-20T00:00:00Z',
    updatedAt: '2025-11-20T00:00:00Z',
  },
  {
    id: 'prod-007',
    name: 'Monolith Notebook Set',
    slug: 'monolith-notebook-set',
    description: 'Three notebooks, infinite possibilities. Premium 100gsm dot-grid paper that resists bleed-through. Lay-flat Swiss binding. Soft-touch covers in Void Black with debossed FNK branding. Includes A4, A5, and pocket sizes. For the thinkers, architects, and dreamers who still believe in analog.',
    shortDesc: '3-piece premium dot-grid notebook set with lay-flat binding.',
    price: 49.99,
    comparePrice: 69.99,
    costPrice: 12.00,
    sku: 'FNK-LN-007',
    categoryId: 'cat-lifestyle',
    images: ['/images/products/notebook-1.jpg', '/images/products/notebook-2.jpg'],
    tags: ['stationery', 'notebook', 'premium', 'analog'],
    isFeatured: false,
    isTrending: false,
    isNew: false,
    inStock: true,
    stockCount: 834,
    weightGrams: 650,
    metadata: { paper: '100gsm dot-grid', sizes: 'A4, A5, Pocket' },
    rating: 4.4,
    reviewCount: 312,
    createdAt: '2025-08-01T00:00:00Z',
    updatedAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'prod-008',
    name: 'Flux Aroma Diffuser',
    slug: 'flux-aroma-diffuser',
    description: 'Transform any room in seconds. Ultrasonic cold-mist technology with whisper-quiet operation at just 22dB. Smart app control lets you schedule sessions and choose from 12 ambient light modes. Handcrafted ceramic body with a matte volcanic finish. Includes a starter set of three exclusive FNK essential oil blends.',
    shortDesc: 'Smart ultrasonic diffuser with 12 light modes and app control.',
    price: 69.99,
    comparePrice: null,
    costPrice: 18.00,
    sku: 'FNK-LD-008',
    categoryId: 'cat-lifestyle',
    images: ['/images/products/diffuser-1.jpg', '/images/products/diffuser-2.jpg'],
    tags: ['home', 'wellness', 'smart', 'aromatherapy'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    inStock: true,
    stockCount: 267,
    weightGrams: 450,
    metadata: { noise: '22dB', modes: '12 light modes' },
    rating: 4.6,
    reviewCount: 198,
    createdAt: '2025-07-15T00:00:00Z',
    updatedAt: '2025-07-15T00:00:00Z',
  },

  // ─── ACCESSORIES ──────────────────────────
  {
    id: 'prod-009',
    name: 'Shadow Ops Crossbody Bag',
    slug: 'shadow-ops-crossbody-bag',
    description: 'Stealth utility meets street-ready design. CORDURA 1000D ballistic nylon with YKK AquaGuard zippers. Hidden RFID-blocking pocket, expandable main compartment, and magnetic buckle system. Reflective 3M accents for night visibility. From daily commutes to weekend adventures — this bag handles everything.',
    shortDesc: 'CORDURA 1000D crossbody with RFID protection and 3M accents.',
    price: 89.99,
    comparePrice: 119.99,
    costPrice: 26.00,
    sku: 'FNK-AB-009',
    categoryId: 'cat-accessories',
    images: ['/images/products/bag-1.jpg', '/images/products/bag-2.jpg'],
    tags: ['bag', 'crossbody', 'edc', 'cordura'],
    isFeatured: true,
    isTrending: true,
    isNew: true,
    inStock: true,
    stockCount: 156,
    weightGrams: 340,
    metadata: { material: 'CORDURA 1000D', capacity: '6L expandable' },
    rating: 4.7,
    reviewCount: 289,
    createdAt: '2025-12-05T00:00:00Z',
    updatedAt: '2025-12-05T00:00:00Z',
  },
  {
    id: 'prod-010',
    name: 'Apex Carbon Fiber Wallet',
    slug: 'apex-carbon-fiber-wallet',
    description: 'The wallet reimagined for the next decade. Real carbon fiber shell weighing just 45g. Spring-loaded card mechanism fans out up to 12 cards instantly. Integrated RFID shield protects your data. Slim enough for any pocket, tough enough for any situation. The wallet that makes leather feel obsolete.',
    shortDesc: 'Ultra-slim carbon fiber wallet with spring-loaded card access.',
    price: 59.99,
    comparePrice: 79.99,
    costPrice: 15.00,
    sku: 'FNK-AW-010',
    categoryId: 'cat-accessories',
    images: ['/images/products/wallet-1.jpg', '/images/products/wallet-2.jpg'],
    tags: ['wallet', 'carbon-fiber', 'edc', 'rfid'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    inStock: true,
    stockCount: 523,
    weightGrams: 45,
    metadata: { material: 'Carbon Fiber', capacity: '12 cards' },
    rating: 4.5,
    reviewCount: 445,
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2025-06-01T00:00:00Z',
  },
  {
    id: 'prod-011',
    name: 'Stealth Watch — Matte Edition',
    slug: 'stealth-watch-matte-edition',
    description: 'Time, stripped to its essence. 40mm surgical-grade 316L stainless steel case with DLC matte coating. Sapphire crystal with AR coating, Japanese Miyota automatic movement, and 100m water resistance. The perforated FKM rubber strap breathes on your wrist. Minimal dial, maximum presence.',
    shortDesc: 'DLC-coated automatic watch with sapphire crystal — 100m WR.',
    price: 299.99,
    comparePrice: 399.99,
    costPrice: 95.00,
    sku: 'FNK-AW-011',
    categoryId: 'cat-accessories',
    images: ['/images/products/watch-1.jpg', '/images/products/watch-2.jpg'],
    tags: ['watch', 'automatic', 'premium', 'stealth'],
    isFeatured: true,
    isTrending: false,
    isNew: true,
    inStock: true,
    stockCount: 67,
    weightGrams: 92,
    metadata: { movement: 'Miyota Automatic', waterResistance: '100m' },
    rating: 4.9,
    reviewCount: 134,
    createdAt: '2025-12-15T00:00:00Z',
    updatedAt: '2025-12-15T00:00:00Z',
  },
  {
    id: 'prod-012',
    name: 'Hex Sunglasses — Titanium Frame',
    slug: 'hex-sunglasses-titanium-frame',
    description: 'Engineered for those who live in the sun. Beta-titanium frames weigh just 18g. Polarized Carl Zeiss lenses with UV400 protection and anti-scratch coating. Hexagonal geometry inspired by carbon molecular structures. Comes with a magnetic hardshell case and microfiber pouch. Designed to be noticed.',
    shortDesc: 'Beta-titanium hexagonal frames with Zeiss polarized lenses.',
    price: 189.99,
    comparePrice: null,
    costPrice: 48.00,
    sku: 'FNK-AS-012',
    categoryId: 'cat-accessories',
    images: ['/images/products/sunglasses-1.jpg', '/images/products/sunglasses-2.jpg'],
    tags: ['sunglasses', 'titanium', 'polarized', 'premium'],
    isFeatured: false,
    isTrending: false,
    isNew: false,
    inStock: true,
    stockCount: 203,
    weightGrams: 18,
    metadata: { material: 'Beta-Titanium', lenses: 'Carl Zeiss Polarized' },
    rating: 4.6,
    reviewCount: 178,
    createdAt: '2025-05-01T00:00:00Z',
    updatedAt: '2025-05-01T00:00:00Z',
  },
]

export const reviews: Review[] = [
  {
    id: 'rev-001',
    productId: 'prod-001',
    userId: 'user-001',
    userName: 'Alex Chen',
    rating: 5,
    title: 'Best earbuds I have ever owned',
    body: 'The ANC is insane and the battery life is no joke. Went through a whole week of commuting before I needed to charge. The sound quality is chef kiss.',
    verified: true,
    createdAt: '2025-12-20T00:00:00Z',
  },
  {
    id: 'rev-002',
    productId: 'prod-001',
    userId: 'user-002',
    userName: 'Sarah Kim',
    rating: 5,
    title: 'Worth every penny',
    body: 'I was skeptical at first but these completely replaced my over-ear headphones. The fit is perfect and they stay put during workouts.',
    verified: true,
    createdAt: '2025-12-18T00:00:00Z',
  },
  {
    id: 'rev-003',
    productId: 'prod-004',
    userId: 'user-003',
    userName: 'Marcus Rivera',
    rating: 5,
    title: 'The thock is real',
    body: 'This keyboard sounds and feels incredible. Hot-swap switches are a game changer. Already swapped in some custom linears and it is perfection.',
    verified: true,
    createdAt: '2025-12-22T00:00:00Z',
  },
  {
    id: 'rev-004',
    productId: 'prod-009',
    userId: 'user-004',
    userName: 'Jordan Blake',
    rating: 4,
    title: 'Solid everyday carry',
    body: 'The build quality is excellent. Love the RFID pocket and magnetic buckle. Only wish it was slightly larger for a full-size tablet.',
    verified: true,
    createdAt: '2025-12-19T00:00:00Z',
  },
  {
    id: 'rev-005',
    productId: 'prod-011',
    userId: 'user-005',
    userName: 'Elena Voss',
    rating: 5,
    title: 'Stunning timepiece',
    body: 'The matte DLC coating looks absolutely incredible in person. Photos do not do it justice. The automatic movement is smooth and the weight feels premium without being heavy.',
    verified: true,
    createdAt: '2025-12-23T00:00:00Z',
  },
]

// Helper functions to query mock data
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured)
}

export function getTrendingProducts(): Product[] {
  return products.filter((p) => p.isTrending)
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew)
}

export function getProductReviews(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.categoryId === product.categoryId && p.id !== product.id)
    .slice(0, limit)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug)
}

export function searchProducts(query: string): Product[] {
  const lower = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lower) ||
      p.description.toLowerCase().includes(lower) ||
      p.tags.some((t) => t.toLowerCase().includes(lower))
  )
}
